/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class AMP_STATUS {
  public final static int AMP_ON = 0;
  public final static int AMP_OFF = AMP_ON + 1;
}

