/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class AMPLI_CHANNEL {
  public final static int AMP_NO_CHANNEL = 0;
  public final static int AMP_FRONT_CHANNEL = AMP_NO_CHANNEL + 1;
  public final static int AMP_REAR_CHANNEL = AMP_FRONT_CHANNEL + 1;
  public final static int AMP_END_CHANNEL = AMP_REAR_CHANNEL + 1;
}

