/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class AMPLI_GAINS {
  public final static int NO_GAIN = 0;
  public final static int LOW_GAIN12 = NO_GAIN + 1;
  public final static int HIGH_GAIN26 = LOW_GAIN12 + 1;
  public final static int END_GAIN = HIGH_GAIN26 + 1;
}

