/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class DR_AUDIO_SOURCES {
  public final static int SRC_NO_SOURCE = 0;
  public final static int SRC_TUNER = SRC_NO_SOURCE + 1;
  public final static int SRC_CD = SRC_TUNER + 1;
  public final static int SRC_MP3 = SRC_CD + 1;
  public final static int SRC_CDC = SRC_MP3 + 1;
  public final static int SRC_AUX = SRC_CDC + 1;
  public final static int SRC_PHONE = SRC_AUX + 1;
  public final static int SRC_TTS = SRC_PHONE + 1;
  public final static int SRC_TA_PTY = SRC_TTS + 1;
  public final static int SRC_TTS_ON_AUX = SRC_TA_PTY + 1;
  public final static int SRC_AUX_CONVERGENCE = SRC_TTS_ON_AUX + 1;
  public final static int SRC_MAX_AUDIO_SOURCES = SRC_AUX_CONVERGENCE + 1;
}

