/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class TYPE_SUB_BAND {
  public final static int AM_MW_BAND = 0;
  public final static int AM_KW_BAND = AM_MW_BAND + 1;
}

